package evospex;

import evospex.state.StateSerializer;
import evospex.state.instrumentation.BytecodeUtils;
import evospex.state.instrumentation.Instrumenter;
import evospex.state.mutation.StateMutator;
import org.junit.Test;
import soot.*;
import soot.jimple.*;
import soot.options.Options;

import java.io.FileNotFoundException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

/**
 * StateGenerator class: allows to serialize states from a given JUnit suite
 */
public class StateGenerator {

  private final String targetMethodSignature;
  private SootClass SOOT_TEST_CLASS;
  private SootMethod SOOT_TARGET_METHOD;
  private int instrumentations = 0;

  /**
   * Setup all the necessary for Soot
   */
  private void setupSoot() {
    // Setup Soot
    G.reset();
    Options.v().set_prepend_classpath(true);
    Options.v().set_allow_phantom_refs(true);
    Options.v().set_soot_classpath(System.getProperty("java.class.path"));
  }

  /**
   * Constructor
   */
  public StateGenerator(String testSuiteClassName, String targetMethodSignature) {
    this.targetMethodSignature = targetMethodSignature;
    // Load the test suite
    try {
      // Load the test class
      Class.forName(testSuiteClassName);
      setupSoot();
      // Load the Soot class
      SOOT_TEST_CLASS = Scene.v().loadClassAndSupport(testSuiteClassName);
      Scene.v().loadClassAndSupport("evospex.state.StateSerializer");
      SOOT_TEST_CLASS.setApplicationClass();
      Scene.v().loadNecessaryClasses();
      try {
        SOOT_TARGET_METHOD = Scene.v().getMethod(targetMethodSignature);
      } catch (RuntimeException e) {
        System.err.println("unable to find method: " + targetMethodSignature);
        // Get the class name from the signature
        String className = targetMethodSignature.substring(1, targetMethodSignature.indexOf(":"));
        System.err.println("possible methods for class " + className + ":");
        for (SootMethod method : Scene.v().getSootClass(className).getMethods()) {
          System.err.println("  " + method.getSignature());
        }
        System.exit(1);
      }
      // Show some info
      System.out.println("target class: "+SOOT_TEST_CLASS.getName());
      System.out.println("target method: "+SOOT_TARGET_METHOD.getSignature());
      System.out.println();
      // Instrument the invocations to the target method
      instrumentInvocationsToTargetMethod();
    } catch (ClassNotFoundException e) {
      System.err.println("The test suite class " + testSuiteClassName + " can't be loaded. Is it in the classpath?");
      System.exit(1);
    }
  }

  /**
   * Instrument all the invocations to the target method within the test class
   */
  private void instrumentInvocationsToTargetMethod() {
    System.out.println("--> target method invocations instrumentation and execution");
    for (SootMethod method : SOOT_TEST_CLASS.getMethods()) {
      performInstrumentation(method);
    }
    System.out.println("invocations instrumented: "+instrumentations);
    System.out.println();
  }

  /**
   * Perform the instrumentation of the given method
   */
  private void performInstrumentation(SootMethod method) {
    // Inspect each unit within the method
    Body methodBody = method.retrieveActiveBody();
    List<Stmt> unitsToInstrument = new ArrayList<>();
    for (Unit unit : methodBody.getUnits()) {
      if (unit instanceof InvokeStmt) {
        InvokeStmt invokeStmt = (InvokeStmt)unit;
        boolean methodMatch = invokeStmt.getInvokeExpr().getMethod().getSignature().equals(targetMethodSignature);
        if (methodMatch) {
          unitsToInstrument.add(invokeStmt);
        }
      }
      if (unit instanceof AssignStmt) {
        AssignStmt assignStmt = (AssignStmt)unit;
        boolean methodMatch = assignStmt.getRightOp() instanceof InvokeExpr && ((InvokeExpr)assignStmt.getRightOp()).getMethod().getSignature().equals(targetMethodSignature);
        if (methodMatch) {
          unitsToInstrument.add(assignStmt);
        }
      }
    }

    // Instrument the invocations
    for (Stmt stmt : unitsToInstrument) {
      instrumentations++;
      Instrumenter.insertCallsToSaveInputState(method, methodBody.getUnits(), stmt);
      Instrumenter.insertCallsToSaveOutputState(method, methodBody.getUnits(), stmt);
    }

  }

  /**
   * Generate the positive states
   * The positive states are generated by running the test suite and serializing objects
   * before and after the invocation of the target method.
   */
  public void generatePositiveStates() throws InstantiationException, IllegalAccessException, FileNotFoundException, ClassNotFoundException {
    // Get the list of test methods
    System.out.println("--> positive states generation");
    Class<?> instrumentedClass = BytecodeUtils.loadAsClass(SOOT_TEST_CLASS);
    List<Method> testMethods = getRunnableTests(instrumentedClass);
    Object testObject = instrumentedClass.newInstance();
    int testsExecuted = 0;
    int errors = 0;
    for (Method testMethod : testMethods) {
      // Run the test method and let the instrumentation collect the created objects
      try {
        Object result = testMethod.invoke(testObject);
        testsExecuted++;
      } catch (Exception e) {
        // Report the cause, not the exception itself: Method.invoke wraps whatever the test threw
        // in an InvocationTargetException whose getMessage() is always null, which reports every
        // distinct failure as an uninformative "error running test X: null".
        Throwable cause = (e.getCause() != null) ? e.getCause() : e;
        System.err.println("error running test " + testMethod.getName() + ": " + cause);
        errors++;
      }
      // Any target-method invocation whose exception was caught - either by this generated
      // test itself (e.g. Randoop's own try/catch around an expected exception) or by
      // propagating out of testMethod.invoke() above - records an input with no matching
      // output, since insertCallsToSaveOutputState's instrumentation (inserted directly after
      // the invocation) is skipped by exceptional control flow. Discard any such orphaned
      // inputs so in*.xml/out*.xml stay positionally aligned for EvoSpexParameters' tuple
      // reader. A while loop (rather than a single removal) handles a test method that
      // internally catches more than one such exception.
      while (StateSerializer.inputsThis.size() > StateSerializer.outputsThis.size()) {
        int last = StateSerializer.inputsThis.size() - 1;
        StateSerializer.inputsThis.remove(last);
        for (List<Object> args : StateSerializer.inputsArgs) {
          args.remove(args.size() - 1);
        }
      }
    }
    System.out.println("tests executed: " + testsExecuted);
    System.out.println("errors: " + errors);
    System.out.println("states generated: " + StateSerializer.outputsThis.size());
    System.out.println();
  }

  /**
   * Generate the negative states
   * The negative states are generated by 'mutating' the positive states.
   * Mutation are applied to the objects after the invocation of the target method.
   */
  public void generateNegativeStates() {
    // Load the positive states
    System.out.println("--> negative states generation");
    List<Object> outputStates = StateSerializer.outputsThis;
    int mutationsToPerform = outputStates.size();
    List<Object> outputResultStates = StateSerializer.outputsResult;
    boolean resultsExist = outputResultStates.size() > 0;

    // Generate a negative state from each positive state by mutating exactly one of 'this' or
    // 'result' - never both - so a negative example differs from its positive counterpart in a
    // single, unambiguous place.
    int swaps = 0;
    int fieldMutations = 0;
    int resultMutations = 0;
    Random rnd = new Random();
    for (int i = 0; i < mutationsToPerform; i++) {
      Object thisState = outputStates.get(i);
      boolean fieldsAvailable = StateMutator.hasEvaluableFields(SOOT_TARGET_METHOD, thisState);
      boolean mutateResultChannel = resultsExist && (!fieldsAvailable || rnd.nextBoolean());

      if (mutateResultChannel) {
        // Mutate only the result; keep 'this' unchanged.
        StateSerializer.serializeMutatedObject(0, thisState, null);
        Object mutatedResult = StateMutator.mutateState(SOOT_TARGET_METHOD, outputResultStates, i);
        StateSerializer.serializeMutatedObject(1, mutatedResult, StateMutator.getLastMutation());
        resultMutations++;
      } else {
        // Mutate only 'this' (field or swap); keep result unchanged.
        Object mutatedOutput = StateMutator.mutateState(SOOT_TARGET_METHOD, outputStates, i);
        String thisMutationDesc = StateMutator.getLastMutation();
        StateSerializer.serializeMutatedObject(0, mutatedOutput, thisMutationDesc);
        if (resultsExist) {
          StateSerializer.serializeMutatedObject(1, outputResultStates.get(i), null);
        }
        if (thisMutationDesc.contains("[Swap Mutation]")) {
          swaps++;
        } else if (thisMutationDesc.contains("[Field Mutation]")) {
          fieldMutations++;
        }
      }
    }
    System.out.println("mutations: " + mutationsToPerform);
    System.out.println("swaps: " + swaps);
    System.out.println("field mutations: " + fieldMutations);
    System.out.println("result mutations: " + resultMutations);
    System.out.println("states generated: " + StateSerializer.mutatedThis.size());
    System.out.println();
  }

  /**
   * Get the list of runnable tests in the given test class
   * A test method is runnable if it is annotated with @Test.
   * @param clazz the test class
   * @return the list of methods corresponding to runnable tests
   */
  private List<Method> getRunnableTests(Class<?> clazz) {
    // Use reflection to find all the JUnit tests in the class
    ArrayList<Method> testMethods = new ArrayList<>();
    for (Method method : clazz.getDeclaredMethods()) {
      if (method.isAnnotationPresent(Test.class)) {
        testMethods.add(method);
      }
    }
    return testMethods;
  }

  /**
   * Get the target method
   * @return the target method
   */
  public SootMethod getTargetMethod() {
    return SOOT_TARGET_METHOD;
  }

  /**
   * Main method
   * @param args the command line arguments: <testSuiteClassName> <targetMethodSignature>
   */
  public static void main(String[] args) {
    if (args.length != 2) {
      System.err.println("Usage: java -cp <cp> evospex.StateGenerator <testSuiteClassName> <targetMethodSignature>");
      System.err.println("provided " + args.length + " args: "+ Arrays.toString(args));
      System.exit(1);
    }
    System.out.println("> State Generation");
    StateGenerator sg = new StateGenerator(args[0], args[1]);
    StateSerializer.setup(sg.getTargetMethod());
    try {
      // Generate the states
      sg.generatePositiveStates();
      sg.generateNegativeStates();
      // Save the serialized states
      StateSerializer.saveSerialization();
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
    System.out.println("Done!");
  }

}